services:
    xiradorn.xzenpages.controller:
        class: xiradorn\xzenpages\controller\main
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'

    xiradorn.xzenpages.listener:
        class: xiradorn\xzenpages\event\main_listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@user'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
